on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app
    
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: '15.x'
    - uses: subosito/flutter-action@v1.4.0
      with:
        channel: 'stable'
    - run: cd app/
    - run: flutter pub get
    - run: flutter build aot
    - run: flutter analyze
