name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.4.0
        with:
          java-version: "16"
          distribution: "adopt"
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: flutter analyze
